name: Deploy to Firebase IF tests pass
on:
  push:
    branches:
      - main
jobs: 
  test:
    uses: ./.github/workflows/run-tests.yml
  build_and_deploy:
    needs: test
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/.pnpm-store           # or pnpm store path
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
      - run: npm install -g pnpm && pnpm install
      - run: pnpm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRYSTERO_3E31B }}
          channelId: live
          projectId: trystero-3e31b
